# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 16:10
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0014_auto_20161119_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioCategoryRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Szenarienbewertung zur Kategorie')),
                ('cateogory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Category')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('belongs_to_category', models.ManyToManyField(to='app.Category', verbose_name='Gehört zu den folgenden Kategorien')),
                ('used_as_filter_by', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Benutzer die diese Subkategorie als Szenariofilter verwenden')),
            ],
        ),
        migrations.AddField(
            model_name='producttype',
            name='used_as_product_type_filter_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Als Produkttypfilter verwendet von'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(default=0.5412317777350767, max_length=200),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='url_name',
            field=models.CharField(default=0.6237504015110755, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='categories',
            field=models.ManyToManyField(through='app.ScenarioCategoryRating', to='app.Category', verbose_name='Bewertung'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='url_name',
            field=models.CharField(default=0.9192080939849578, max_length=100, verbose_name='URL-Name'),
        ),
        migrations.AddField(
            model_name='scenariocategoryrating',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Scenario'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='subcategory',
            field=models.ManyToManyField(to='app.SubCategory', verbose_name='Dieses Szenario ist Teil dieser Subkategorie'),
        ),
    ]
