# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 12:06
from __future__ import unicode_literals

import app.validators
from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, validators=[app.validators.validate_legal_chars])),
                ('picture', models.ImageField(upload_to='categories', verbose_name='Bild für die Kategorie')),
                ('backgroundPicture', models.ImageField(blank=True, null=True, upload_to='categories', verbose_name='Bild für den Hintergrund')),
                ('short_description', models.TextField(default='---', max_length=170, verbose_name='Kurzbeschreibung')),
                ('description', models.TextField(default='---', verbose_name='Beschreibung')),
                ('iconString', models.CharField(default='gift', max_length=20, verbose_name='Zu verwendenes Icon')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Kategorien',
                'verbose_name': 'Kategorie',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_title', models.CharField(max_length=255, verbose_name='Kommentartitel')),
                ('comment_content', models.TextField(verbose_name='Kommentarinhalt')),
                ('rating', models.PositiveSmallIntegerField(default='0', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Bewertung')),
                ('creation_date', models.DateTimeField()),
                ('page_url', models.CharField(default='', max_length=255)),
            ],
            options={
                'ordering': ['-creation_date', 'comment_title', '-rating'],
                'verbose_name_plural': 'Kommentare',
                'verbose_name': 'Kommentar',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['username'],
                'verbose_name_plural': 'Angestellte',
                'verbose_name': 'Angestellter',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('serial_number', models.CharField(default='------', max_length=255, verbose_name='Artikelnummer')),
                ('description', models.TextField(verbose_name='Berschreibung')),
                ('specifications', models.TextField(default='---', verbose_name='Technische Details')),
                ('image1', models.ImageField(upload_to='products', verbose_name='Bild 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='products', verbose_name='Bild 2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='products', verbose_name='Bild 3')),
                ('end_of_life', models.BooleanField(default=False, verbose_name='EOL')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Produkte',
                'verbose_name': 'Produkt',
            },
        ),
        migrations.CreateModel(
            name='ProductSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='------', max_length=100)),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Produktsammlungen',
                'verbose_name': 'Produktsammlung',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=255, unique=True, verbose_name='Artname')),
            ],
            options={
                'ordering': ['type_name'],
                'verbose_name_plural': 'Produktarten',
                'verbose_name': 'Produktart',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=0.6491577644961926, max_length=200)),
                ('is_visible', models.BooleanField(default=False, verbose_name='sichtbar')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Hersteller',
                'verbose_name': 'Hersteller',
            },
        ),
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_name', models.CharField(max_length=200, unique=True, verbose_name='öffentlicher Name')),
                ('url_name', models.CharField(default=0.7125224779103091, max_length=200, unique=True)),
                ('logo_image', models.ImageField(help_text='Dieses Logo wird nur bei den Produkten als kleines Icon angezeigt.', upload_to='provider', verbose_name='Provider Logo für Szenarien und Produkte')),
                ('profile_image', models.ImageField(null=True, upload_to='provider', verbose_name='Bild für die Profilseite')),
                ('banner_image', models.ImageField(upload_to='provider', verbose_name='Banner für Profilseite')),
                ('introduction', models.TextField(verbose_name='Einleitung')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Kontakt-Email')),
                ('website', models.URLField()),
                ('owner', models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='app.Provider', verbose_name='Eigentümer')),
            ],
            options={
                'ordering': ['public_name'],
                'verbose_name_plural': 'Herstellerprofile',
                'verbose_name': 'Herstellerprofil',
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('url_name', models.CharField(default=0.45231143347673775, max_length=100, verbose_name='URL-Name')),
                ('short_description', models.TextField(blank=True, max_length='80', null=True, verbose_name='Kurzbeschreibung')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='scenarios', verbose_name='Bild')),
                ('categories', models.ManyToManyField(to='app.Category', verbose_name='passende Kategorien')),
                ('provider', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='app.Provider', verbose_name='Versorger')),
                ('scenario_product_set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.ProductSet', verbose_name='dazugehörige Produktsammlung')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Szenarien',
                'verbose_name': 'Szenario',
            },
        ),
        migrations.CreateModel(
            name='ScenarioDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('image', models.ImageField(upload_to='scenarioDesc', verbose_name='Bild')),
                ('left_right', models.BooleanField(verbose_name='Bild auf der rechten Seite zeigen')),
                ('order', models.IntegerField(verbose_name='Reihenfolge')),
                ('belongs_to_scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Scenario', verbose_name='Beschreibung für Szenario')),
            ],
            options={
                'ordering': ['order'],
                'verbose_name_plural': 'Szenariobeschreibungen',
                'verbose_name': 'Szenariobeschreibung',
            },
        ),
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='user', verbose_name='Bild')),
                ('belongs_to_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='gehört zu Nutzer')),
            ],
            options={
                'ordering': ['belongs_to_user'],
                'verbose_name_plural': 'Nutzbilder',
                'verbose_name': 'Nutzerbild',
            },
        ),
        migrations.AddField(
            model_name='productset',
            name='creator',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='app.Provider', verbose_name='Ersteller'),
        ),
        migrations.AddField(
            model_name='productset',
            name='products',
            field=models.ManyToManyField(to='app.Product', verbose_name='Dazugehörige Produkte'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='app.ProductType', verbose_name='Produktart'),
        ),
        migrations.AddField(
            model_name='product',
            name='provider',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='app.Provider', verbose_name='Produzent'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Provider'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
