# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160622_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('answer_presentation', models.CharField(choices=[('mc', 'Multiple Choice'), ('rc', 'Radiobutton'), ('dc', 'Dropdown'), ('sc', 'Slider')], default='mc', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='productset',
            name='description',
            field=models.TextField(blank=True, help_text='Wenn dieses Produktset zu einem Szenario gehört,dann geben Sie das bitte hier mit an', verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(default=0.14508934286869202, max_length=200),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='url_name',
            field=models.CharField(default=0.7153433188909024, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='url_name',
            field=models.CharField(default=0.14670940057816606, max_length=100, verbose_name='URL-Name'),
        ),
        migrations.AddField(
            model_name='answer',
            name='belongs_to_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Tag'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='app.Tag', verbose_name='Schlagwörter'),
        ),
        migrations.AddField(
            model_name='productset',
            name='tags',
            field=models.ManyToManyField(to='app.Tag', verbose_name='Schlagwörter'),
        ),
    ]
