# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160522_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='picture',
            field=models.ImageField(upload_to='media/categories', verbose_name='image for category'),
        ),
    ]
