# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 10:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_auto_20160622_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='GivenAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'beantwortete Antworten',
                'verbose_name': 'beantwortete Antwort',
            },
        ),
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='---', max_length=255)),
                ('category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Category', verbose_name='Dazugehörige Kategorie')),
                ('question', models.ManyToManyField(to='app.Product', verbose_name='Dazugehörige Fragen')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Fragensammlungen',
                'verbose_name': 'Fragensammlung',
            },
        ),
        migrations.CreateModel(
            name='SessionTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.Session', verbose_name='Zugehörige Session')),
            ],
            options={
                'verbose_name_plural': 'Session Tags',
                'verbose_name': 'Session Tag',
            },
        ),
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['belongs_to_question_id', 'pk'], 'verbose_name': 'Antwort', 'verbose_name_plural': 'Antworten'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Frage', 'verbose_name_plural': 'Fragen'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['code'], 'verbose_name': 'Schlagwort', 'verbose_name_plural': 'Schlagwörter'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.CharField(max_length=255, verbose_name='Anworttext'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='belongs_to_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Question', verbose_name='gehört zu Frage'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Tag', verbose_name='Schlagwort'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_content',
            field=models.TextField(verbose_name='Inhalt'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='geschrieben von'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_title',
            field=models.CharField(max_length=255, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellungsdatum'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='page_url',
            field=models.CharField(default='', max_length=255, verbose_name='Seiten-URL'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Provider', verbose_name='Arbeitgeber'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='type_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(default=0.3419643179868058, max_length=200),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='url_name',
            field=models.CharField(default=0.9691685706107375, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_presentation',
            field=models.CharField(choices=[('mc', 'Multiple Choice'), ('rc', 'Radiobutton'), ('dc', 'Dropdown'), ('sc', 'Slider'), ('rs', 'Range Slider')], default='mc', max_length=2, verbose_name='Anzeigenart der Anworten'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=255, verbose_name='Fragentext'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='url_name',
            field=models.CharField(default=0.6881810738562697, max_length=100, verbose_name='URL-Name'),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user', verbose_name='Nutzerbild'),
        ),
        migrations.AddField(
            model_name='sessiontags',
            name='tag',
            field=models.ManyToManyField(to='app.Tag', verbose_name='Referenziert auf Tag'),
        ),
        migrations.AddField(
            model_name='givenanswers',
            name='user_answer',
            field=models.ManyToManyField(to='app.Answer', verbose_name='hat geantwortet'),
        ),
    ]
