# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160522_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='picture',
            field=models.ImageField(upload_to='categories', verbose_name='image for category'),
        ),
    ]
