# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160522_1257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategorie', 'verbose_name_plural': 'Kategorien'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produkt', 'verbose_name_plural': 'Produkte'},
        ),
        migrations.AlterModelOptions(
            name='productset',
            options={'verbose_name': 'Produktsammlung', 'verbose_name_plural': 'Produktsammlungen'},
        ),
        migrations.AlterModelOptions(
            name='scenario',
            options={'verbose_name': 'Szenario', 'verbose_name_plural': 'Szenarien'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='categories',
        ),
        migrations.AddField(
            model_name='category',
            name='scenario_set',
            field=models.ManyToManyField(to='app.Scenario', verbose_name='Zur Kategorie gehörende Szenarien'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='picture',
            field=models.ImageField(upload_to='categories', verbose_name='Bild für die Kategorie'),
        ),
        migrations.AlterField(
            model_name='productset',
            name='description',
            field=models.TextField(blank=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='productset',
            name='products',
            field=models.ManyToManyField(to='app.Product', verbose_name='Dazugehörige Produkte'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='description',
            field=models.TextField(verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='picture',
            field=models.ImageField(upload_to='', verbose_name='Bild'),
        ),
    ]
