# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-05 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160630_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order', 'pk'], 'verbose_name': 'Frage', 'verbose_name_plural': 'Fragen'},
        ),
        migrations.AlterModelOptions(
            name='questionset',
            options={'ordering': ['order', 'pk'], 'verbose_name': 'Fragensammlung', 'verbose_name_plural': 'Fragensammlungen'},
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='questionset',
            name='order',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(default=0.23097310427384088, max_length=200),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='url_name',
            field=models.CharField(default=0.3778445651437188, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='url_name',
            field=models.CharField(default=0.04725457222510254, max_length=100, verbose_name='URL-Name'),
        ),
        migrations.AddField(
            model_name='questionstep',
            name='question_steps',
            field=models.ManyToManyField(to='app.QuestionSet'),
        ),
    ]
