# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-05 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20160705_1020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionstep',
            options={'verbose_name': 'Fragen für Stepper-Schritt', 'verbose_name_plural': 'Fragen für Stepper-Schritte'},
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(default=0.9044316984039541, max_length=200),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='url_name',
            field=models.CharField(default=0.19684467478580403, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='questionstep',
            name='question_steps',
            field=models.ManyToManyField(to='app.QuestionSet', verbose_name='zusammen gehörende Fragen'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='url_name',
            field=models.CharField(default=0.08257657570719712, max_length=100, verbose_name='URL-Name'),
        ),
    ]
