# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='short_description',
            field=models.TextField(blank=True, max_length='255', null=True, verbose_name='Kurzbeschreibung'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Bild'),
        ),
    ]
