# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 17:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20160526_1244'),
        ('app', '0007_auto_20160526_1239'),
    ]

    operations = [
    ]
