# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-08 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20160718_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiontags',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(default=0.1635791108347271, max_length=200),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='url_name',
            field=models.CharField(default=0.9806983468176363, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_presentation',
            field=models.CharField(choices=[('mc', 'Multiple Choice'), ('rc', 'Radiobutton'), ('dc', 'Dropdown')], default='mc', max_length=2, verbose_name='Anzeigenart der Anworten'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='url_name',
            field=models.CharField(default=0.6401940897381623, max_length=100, verbose_name='URL-Name'),
        ),
    ]
