# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_merge'),
        ('app', '0005_auto_20160524_1855'),
    ]

    operations = [
    ]
