# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20160808_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Product')),
            ],
            bases=('app.product',),
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Product')),
            ],
            bases=('app.product',),
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MetaDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(default=0.2523720231934079, max_length=200),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='url_name',
            field=models.CharField(default=0.3217408117272177, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_presentation',
            field=models.CharField(choices=[('mc', 'Multiple Choice'), ('rc', 'Radiobutton'), ('dc', 'Dropdown'), ('sc', 'Slider')], default='mc', max_length=2, verbose_name='Anzeigenart der Anworten'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='url_name',
            field=models.CharField(default=0.023276841818113625, max_length=100, verbose_name='URL-Name'),
        ),
        migrations.CreateModel(
            name='MetaBroker',
            fields=[
                ('metadevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.MetaDevice')),
            ],
            bases=('app.metadevice',),
        ),
        migrations.CreateModel(
            name='MetaEndpoint',
            fields=[
                ('metadevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.MetaDevice')),
            ],
            bases=('app.metadevice',),
        ),
        migrations.AddField(
            model_name='metadevice',
            name='implementation_requires',
            field=models.ManyToManyField(to='app.Feature', verbose_name='Definiert von folgender Featuresammlung'),
        ),
        migrations.AddField(
            model_name='metadevice',
            name='productSet',
            field=models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ProductSet', verbose_name='Produktset'),
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.ManyToManyField(to='app.Feature', verbose_name='Hat Features'),
        ),
        migrations.AddField(
            model_name='product',
            name='protocol',
            field=models.ManyToManyField(to='app.Protocol', verbose_name='Spricht Protokoll'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='meta_devices',
            field=models.ManyToManyField(to='app.MetaDevice', verbose_name='Besteht aus MetaDevices'),
        ),
    ]
