# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20161119_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionset',
            name='category',
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(default=0.9424947507899236, max_length=200),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='url_name',
            field=models.CharField(default=0.4630074869810098, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='url_name',
            field=models.CharField(default=0.2265351401171768, max_length=100, verbose_name='URL-Name'),
        ),
    ]
