# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 13:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20160529_1339'),
        ('app', '0005_auto_20160524_0947'),
    ]

    operations = [
    ]
