# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20160529_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
