# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_provider_is_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('left_right', models.BooleanField()),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='scenario',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AddField(
            model_name='scenariodescription',
            name='belongs_to_scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Scenario'),
        ),
    ]
