# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20160602_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
