# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20161119_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='tag',
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(default=0.7860604636493711, max_length=200),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='url_name',
            field=models.CharField(default=0.12440561747787082, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='url_name',
            field=models.CharField(default=0.6014038152423459, max_length=100, verbose_name='URL-Name'),
        ),
    ]
