# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20160602_1455'),
        ('app', '0012_auto_20160602_1340'),
    ]

    operations = [
    ]
