# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20160605_1328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scenariodescription',
            options={'verbose_name': 'Szenariobeschreibung', 'verbose_name_plural': 'Szenariobeschreibungen'},
        ),
        migrations.AlterField(
            model_name='productset',
            name='name',
            field=models.CharField(default='------', max_length=100),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='type_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
