# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20160605_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(upload_to='products', verbose_name='Bild 1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='products', verbose_name='Bild 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='products', verbose_name='Bild 3'),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='banner_image',
            field=models.ImageField(upload_to='provider', verbose_name='Provider Banner'),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='logo_image',
            field=models.ImageField(upload_to='provider', verbose_name='Provider Logo'),
        ),
    ]
