# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 15:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0013_auto_20161119_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingBasket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(default=0.23235367199105306, max_length=200),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='url_name',
            field=models.CharField(default=0.6415987975834807, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='url_name',
            field=models.CharField(default=0.8525076247591117, max_length=100, verbose_name='URL-Name'),
        ),
        migrations.AddField(
            model_name='shoppingbasket',
            name='scenarios',
            field=models.ManyToManyField(to='app.Scenario', verbose_name='Szenarios die Teil dieses Einkaufswagens sind'),
        ),
        migrations.AddField(
            model_name='shoppingbasket',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Besitzer dieses Einkaufswagens'),
        ),
    ]
