# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20160605_1538'),
        ('app', '0014_auto_20160605_1406'),
    ]

    operations = [
    ]
