# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 08:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_merge'),
        ('app', '0015_merge'),
    ]

    operations = [
    ]
