# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20161119_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='categories',
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(default=0.5727892889905223, max_length=200),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='url_name',
            field=models.CharField(default=0.6489338819190672, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='url_name',
            field=models.CharField(default=0.2691362781652099, max_length=100, verbose_name='URL-Name'),
        ),
    ]
