# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='provider', verbose_name='Bild für die Profilseite'),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='banner_image',
            field=models.ImageField(upload_to='provider', verbose_name='Banner für Profilseite'),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='logo_image',
            field=models.ImageField(upload_to='provider', verbose_name='Provider Logo für Szenarien und Produkte'),
        ),
    ]
