# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20160607_0940'),
        ('app', '0016_merge'),
    ]

    operations = [
    ]
