# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 16:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20161121_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioCategoryRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Passfähigkeit')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Category', verbose_name='Kategorie')),
            ],
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(default=0.6112896865723758, max_length=200),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='url_name',
            field=models.CharField(default=0.44937907781318664, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='url_name',
            field=models.CharField(default=0.5322631618289846, max_length=100, verbose_name='URL-Name'),
        ),
        migrations.AddField(
            model_name='scenariocategoryrating',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Scenario', verbose_name='Szenario'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='categories',
            field=models.ManyToManyField(through='app.ScenarioCategoryRating', to='app.Category', verbose_name='Bewertung'),
        ),
    ]
