# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 15:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20161121_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productset',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='productset',
            name='products',
        ),
        migrations.RemoveField(
            model_name='productset',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='sessiontags',
            name='session',
        ),
        migrations.RemoveField(
            model_name='sessiontags',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='shoppingbasket',
            name='scenarios',
        ),
        migrations.RemoveField(
            model_name='shoppingbasket',
            name='user',
        ),
        migrations.RemoveField(
            model_name='metadevice',
            name='productSet',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='scenario_product_set',
        ),
        migrations.AddField(
            model_name='protocol',
            name='is_leader',
            field=models.BooleanField(default=False, verbose_name='Kann als Broker fungieren'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='used_as_product_type_filter_by',
            field=models.ManyToManyField(to='sessions.Session', verbose_name='Als Produkttypfilter verwendet von'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(default=0.37170672839397945, max_length=200),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='url_name',
            field=models.CharField(default=0.14840430616439682, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='url_name',
            field=models.CharField(default=0.14826886965221742, max_length=100, verbose_name='URL-Name'),
        ),
        migrations.AlterField(
            model_name='scenariocategoryrating',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Passfaehigkeit'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='used_as_filter_by',
            field=models.ManyToManyField(to='sessions.Session', verbose_name='Benutzer die diese Subkategorie als Szenariofilter verwenden'),
        ),
        migrations.DeleteModel(
            name='ProductSet',
        ),
        migrations.DeleteModel(
            name='SessionTags',
        ),
        migrations.DeleteModel(
            name='ShoppingBasket',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
