# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20160609_2033'),
        ('app', '0016_merge'),
    ]

    operations = [
    ]
