# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 11:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0017_auto_20160609_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_title', models.CharField(max_length=255, verbose_name='Kommentartitel')),
                ('comment_content', models.TextField(verbose_name='Kommentarinhalt')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='Bewertung')),
                ('creation_date', models.DateTimeField()),
                ('comment_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Kommentare',
                'verbose_name': 'Kommentar',
                'ordering': ['comment_title', 'rating'],
            },
        ),
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='user', verbose_name='Bild')),
                ('belongs_to_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='gehört zu Nutzer')),
            ],
            options={
                'verbose_name_plural': 'Nutzbilder',
                'verbose_name': 'Nutzerbild',
                'ordering': ['belongs_to_user'],
            },
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='logo_image',
            field=models.ImageField(help_text='Dieses Logo wird nur bei den Produkten als kleines Icon angezeigt. ', upload_to='provider', verbose_name='Provider Logo für Szenarien und Produkte'),
        ),
    ]
