# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_category_iconstring'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='backgroundPicture',
            field=models.ImageField(blank=True, null=True, upload_to='categories', verbose_name='Bild für den Hintergrund'),
        ),
    ]
