# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('app', '0018_auto_20161126_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingBasket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(default=0.20511837204080563, max_length=200),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='url_name',
            field=models.CharField(default=0.5370232679893578, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='url_name',
            field=models.CharField(default=0.6514264942420637, max_length=100, verbose_name='URL-Name'),
        ),
        migrations.AddField(
            model_name='shoppingbasket',
            name='scenarios',
            field=models.ManyToManyField(to='app.Scenario', verbose_name='Szenarios die Teil dieses Einkaufswagens sind'),
        ),
        migrations.AddField(
            model_name='shoppingbasket',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sessions.Session', verbose_name='Besitzer dieses Einkaufswagens'),
        ),
    ]
