# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20160612_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='short_description',
            field=models.TextField(default='---', max_length=170, verbose_name='Kurzbeschreibung'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(default='---', verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(default=0.6050650119853649, max_length=200),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='url_name',
            field=models.CharField(default=0.35237306915425515, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='url_name',
            field=models.CharField(default=0.8650354317149799, max_length=100),
        ),
    ]
