# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('app', '0019_auto_20161126_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingbasket',
            name='scenarios',
        ),
        migrations.RemoveField(
            model_name='shoppingbasket',
            name='session',
        ),
        migrations.AddField(
            model_name='scenario',
            name='in_shopping_basket_of',
            field=models.ManyToManyField(to='sessions.Session', verbose_name='Dieses Szenario liegt im Warenkorb von Session'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(default=0.9324919577881733, max_length=200),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='url_name',
            field=models.CharField(default=0.04808120958509898, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='url_name',
            field=models.CharField(default=0.7531086747746215, max_length=100, verbose_name='URL-Name'),
        ),
        migrations.DeleteModel(
            name='ShoppingBasket',
        ),
    ]
