# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_category_backgroundpicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='backgroundPicture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Bild für den Hintergrund'),
        ),
    ]
