# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-03 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20161130_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='meta_devices',
        ),
        migrations.AddField(
            model_name='scenario',
            name='meta_broker',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='app.MetaBroker', verbose_name='Besteht aus einem Metabroker'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='meta_endpoints',
            field=models.ManyToManyField(to='app.MetaEndpoint', verbose_name='Besteht aus MetaEndpointDevices'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='provider',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='app.Provider', verbose_name='Erstellt von'),
        ),
    ]
