# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20160615_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='page_url',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(default=0.8544693716872213, max_length=200),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='url_name',
            field=models.CharField(default=0.8190117852764338, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='url_name',
            field=models.CharField(default=0.205954469590233, max_length=100),
        ),
    ]
