# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 23:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20161130_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='GivenSliderAnswer',
            fields=[
                ('givenanswers_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.GivenAnswers')),
                ('rating_value', models.IntegerField()),
            ],
            bases=('app.givenanswers',),
        ),
        migrations.CreateModel(
            name='SliderQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Question')),
                ('rating_min', models.IntegerField(verbose_name='Minimaler Wert für Antworten')),
                ('rating_max', models.IntegerField(verbose_name='Maximaler Wert für Antworten')),
            ],
            bases=('app.question',),
        ),
        migrations.RemoveField(
            model_name='answerslider',
            name='answer_ptr',
        ),
        migrations.DeleteModel(
            name='AnswerSlider',
        ),
    ]
