# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-03 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20161203_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='used_as_product_type_filter_by',
            field=models.ManyToManyField(blank=True, to='sessions.Session', verbose_name='Als Produkttypfilter verwendet von'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='in_shopping_basket_of',
            field=models.ManyToManyField(blank=True, to='sessions.Session', verbose_name='Dieses Szenario liegt im Warenkorb von Session'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='used_as_filter_by',
            field=models.ManyToManyField(blank=True, to='sessions.Session', verbose_name='Benutzer die diese Subkategorie als Szenariofilter verwenden'),
        ),
    ]
