# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20161202_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='givenslideranswer',
            name='givenanswers_ptr',
        ),
        migrations.RemoveField(
            model_name='sliderquestion',
            name='question_ptr',
        ),
        migrations.DeleteModel(
            name='GivenSliderAnswer',
        ),
        migrations.DeleteModel(
            name='SliderQuestion',
        ),
    ]
