# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20161204_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='givenanswers',
            name='rating_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='rating_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='Maximaler Wert für Antworten'),
        ),
        migrations.AddField(
            model_name='question',
            name='rating_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Minimaler Wert für Antworten'),
        ),
    ]
