# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20161204_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategoryDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('image', models.ImageField(upload_to='scenarioDesc', verbose_name='Bild')),
                ('left_right', models.BooleanField(verbose_name='Bild auf der rechten Seite zeigen')),
                ('order', models.IntegerField(verbose_name='Reihenfolge')),
            ],
            options={
                'verbose_name': 'SubKategoriebeschreibung',
                'ordering': ['order'],
                'verbose_name_plural': 'SubKategoriebeschreibungen',
            },
        ),
        migrations.RemoveField(
            model_name='scenariodescription',
            name='belongs_to_scenario',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='scenarios', verbose_name='Bild'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='short_description',
            field=models.TextField(blank=True, max_length='80', null=True, verbose_name='Kurzbeschreibung'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='url_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='URL-Name'),
        ),
        migrations.DeleteModel(
            name='ScenarioDescription',
        ),
        migrations.AddField(
            model_name='subcategorydescription',
            name='belongs_to_subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SubCategory', verbose_name='Beschreibung für SubKateogrie'),
        ),
    ]
