# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20161204_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='subcategories', verbose_name='Bild'),
        ),
        migrations.AlterField(
            model_name='subcategorydescription',
            name='image',
            field=models.ImageField(upload_to='subcategoryDesc', verbose_name='Bild'),
        ),
    ]
