# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20161204_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='short_description',
        ),
        migrations.AddField(
            model_name='scenario',
            name='description',
            field=models.TextField(blank=True, max_length='500', null=True, verbose_name='Kurzbeschreibung'),
        ),
    ]
