# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20161204_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broker',
            name='product_ptr',
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='product_ptr',
        ),
        migrations.RemoveField(
            model_name='metabroker',
            name='metadevice_ptr',
        ),
        migrations.RemoveField(
            model_name='metaendpoint',
            name='metadevice_ptr',
        ),
        migrations.RemoveField(
            model_name='metadevice',
            name='name',
        ),
        migrations.AddField(
            model_name='metadevice',
            name='is_broker',
            field=models.BooleanField(default=True, verbose_name='Ist das Metadevice ein Broker'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='meta_broker',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meta_broker', to='app.MetaDevice', verbose_name='Besteht aus einem Metabroker'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='meta_endpoints',
            field=models.ManyToManyField(related_name='meta_endpoint', to='app.MetaDevice', verbose_name='Besteht aus MetaEndpointDevices'),
        ),
        migrations.DeleteModel(
            name='Broker',
        ),
        migrations.DeleteModel(
            name='Endpoint',
        ),
        migrations.DeleteModel(
            name='MetaBroker',
        ),
        migrations.DeleteModel(
            name='MetaEndpoint',
        ),
    ]
