# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20161204_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='protocol',
        ),
        migrations.RemoveField(
            model_name='protocol',
            name='is_leader',
        ),
        migrations.AddField(
            model_name='product',
            name='follower_protocol',
            field=models.ManyToManyField(related_name='protocol_follower', to='app.Protocol', verbose_name='Spricht Protokoll im follower modus'),
        ),
        migrations.AddField(
            model_name='product',
            name='leader_protocol',
            field=models.ManyToManyField(related_name='protocol_leader', to='app.Protocol', verbose_name='Spricht Protokoll im leader modus'),
        ),
    ]
