# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20161204_1916'),
        ('app', '0029_auto_20161204_2107'),
    ]

    operations = [
    ]
