# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20161207_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='icon_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
