# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20161210_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='efficiency',
            field=models.IntegerField(default=0, verbose_name='Verbrauch in Watt'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='Preis in Euro'),
        ),
    ]
