# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 23:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20161210_1729'),
        ('app', '0034_auto_20161210_1426'),
    ]

    operations = [
    ]
