# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20161211_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='categories',
            field=models.ManyToManyField(through='app.ScenarioCategoryRating', to='app.Category', verbose_name='Bewertung'),
        ),
    ]
