# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20161211_1634'),
        ('app', '0036_auto_20161211_2355'),
    ]

    operations = [
    ]
