# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_merge_20161212_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='icon_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
