# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_merge_20161212_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='renovation_required',
            field=models.BooleanField(default=False, verbose_name='Erfodert Renovierung'),
        ),
    ]
