# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_answer_icon_name'),
        ('app', '0038_product_renovation_required'),
    ]

    operations = [
    ]
