# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 22:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_merge_20161214_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionset',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questionstep',
            name='question_steps',
        ),
        migrations.DeleteModel(
            name='QuestionSet',
        ),
        migrations.DeleteModel(
            name='QuestionStep',
        ),
    ]
