# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20161214_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(blank=True, max_length=80, verbose_name='Titel für Onboarding'),
        ),
    ]
