# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_question_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Kurzbeschreibung'),
        ),
    ]
