# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-02 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_auto_20161216_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='meta_broker',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='broker_of_scenario', to='app.MetaDevice', verbose_name='Besteht aus einem Metabroker'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='meta_endpoints',
            field=models.ManyToManyField(related_name='ednpoint_of_scenario', to='app.MetaDevice', verbose_name='Besteht aus MetaEndpointDevices'),
        ),
    ]
