# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-31 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_auto_20161216_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='efficiency',
            field=models.FloatField(default=0.0, verbose_name='Verbrauch in Watt'),
        ),
    ]
