# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 10:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_auto_20161231_1249'),
        ('app', '0044_auto_20170102_1311'),
    ]

    operations = [
    ]
