# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-09 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_merge_20170103_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='house_overlay_picture',
            field=models.FileField(blank=True, null=True, upload_to='productType/house_overlay_picture', verbose_name='Bildicon in der Hausvorschau'),
        ),
    ]
