# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_auto_20170110_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='productType/house_overlay_picture', verbose_name='Bildicon'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='svg_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Id des SVG in der Hausvorschau'),
        ),
    ]
