# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 19:00
from __future__ import unicode_literals

from django.db import migrations, models


def migrate_provider_public_name_and_logo_image(apps, schema_editor):
    # see https://docs.djangoproject.com/en/1.10/topics/migrations/#data-migrations
    # for details on how this data migration works
    ProviderProfile = apps.get_model('app', 'ProviderProfile')
    for profile in ProviderProfile.objects.all():
        profile.owner.public_name = profile.public_name
        profile.owner.logo_image = profile.logo_image
        profile.owner.save()

    Provider = apps.get_model('app', 'Provider')
    for provider in Provider.objects.all():
        # some providers don't have a ProviderProfile because someone didn't do
        # enough form validation.
        if provider.public_name == "":
            provider.public_name = provider.name
            provider.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_auto_20170110_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='logo_image',
            field=models.ImageField(default='', help_text='Dieses Logo wird nur bei den Produkten als kleines Icon angezeigt.', upload_to='provider', verbose_name='Provider Logo für Szenarien und Produkte'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='public_name',
            field=models.CharField(default='', max_length=200, unique=False, verbose_name='öffentlicher Name'),
            preserve_default=False,
        ),
        migrations.RunPython(migrate_provider_public_name_and_logo_image),
        migrations.AlterField(
            model_name='provider',
            name='public_name',
            field=models.CharField(default='', max_length=200, unique=True, verbose_name='öffentlicher Name'),
            preserve_default=False,
        )
    ]
