# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 19:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_auto_20170115_1900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='providerprofile',
            options={'verbose_name': 'Herstellerprofil', 'verbose_name_plural': 'Herstellerprofile'},
        ),
        migrations.RemoveField(
            model_name='providerprofile',
            name='logo_image',
        ),
        migrations.RemoveField(
            model_name='providerprofile',
            name='public_name',
        ),
    ]
