# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_auto_20170115_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenariocategoryrating',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_ratings', to='app.Scenario', verbose_name='Szenario'),
        ),
        migrations.AlterUniqueTogether(
            name='scenariocategoryrating',
            unique_together=set([('scenario', 'category')]),
        ),
    ]
