# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 22:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_auto_20170117_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='givenanswers',
            name='user',
        ),
        migrations.RemoveField(
            model_name='givenanswers',
            name='user_answer',
        ),
        migrations.DeleteModel(
            name='GivenAnswers',
        ),
    ]
