# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 07:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_auto_20170116_0641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specifications',
        ),
    ]
