# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 07:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_auto_20170116_0713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='markdown_description',
            new_name='description',
        ),
    ]
