# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_metadevice_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metadevice',
            options={'ordering': ['name']},
        ),
    ]
