# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-28 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_scenario_title'),
        ('app', '0058_auto_20170123_1921'),
    ]

    operations = [
    ]
