PRODUCT_PREF_PRICE = "Preis"
PRODUCT_PREF_EFFICIENCY = "Effizienz"
PRODUCT_PREF_EXTENDABILITY = "Erweiterbarkeit"
MINIMAL_RATING_VALUE = 1
MAXIMAL_RATING_VALUE = 10
SHOPPING_BASKET_PRODUCT_TYPE_FILTER = 'product_type_filter'
SHOPPING_BASKET_SCENARIO_ID = 'scenario_id'
