PRODUCT_PREF_PRICE = "Preis"
PRODUCT_PREF_EFFICIENCY = "Effizienz"
PRODUCT_PREF_EXTENDABILITY = "Erweiterbarkeit"
SUGGESTIONS_INPUT_SESSION_KEY = 'suggestions_input'
MINIMAL_RATING_VALUE = 1
MAXIMAL_RATING_VALUE = 10
